apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-key-collie
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "848904544894"
    kanikoFlags: --skip-unused-stages --snapshotMode=redo
    project: cellular-dream-296612
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - key: dev
    owner: synectiks-sddc
    repository: jx3-gke-gsm
  - key: staging
  - key: production
  ingress:
    domain: 34.70.27.128.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kuberhealthy: true
  pipelineUser:
    username: synectiks-code
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-tf-jx-key-collie-557e981a9613
  - name: reports
    url: gs://reports-tf-jx-key-collie-557e981a9613
  - name: repository
    url: gs://repository-tf-jx-key-collie-557e981a9613
  vault: {}
  webhook: lighthouse
